fragment marketSnapshotFields on MarketSnapshot {
  id
  name
  minPrice
  maxPrice
  medianPrice
  sumPrice
  meanPrice
  volume
  offerCount
  relativeMinPriceFirst5
  relativeMinPriceFirst10
  relativeMinPriceFirst5Pct
  relativeMinPriceFirst10Pct
  relativeMinPriceFirst15Pct
  stdDeviation
  routineAt
  routineAtTime
  updatedAt
  updatedAtTime
}

query MarketSnapshot {
  marketSnapshot {
    ...marketSnapshotFields
  }
}
