export const items: any = {
  3: {
    id: 3,
    name: 'Air Essence',
    itemImage: '/images/runecrafting/air_talisman.png',
    class: 'rune',
  },
  4: {
    id: 4,
    name: 'Earth Essence',
    itemImage: '/images/runecrafting/earth_talisman.png',
    class: 'rune',
  },
  5: {
    id: 5,
    name: 'Fire Essence',
    itemImage: '/images/runecrafting/fire_talisman.png',
    class: 'rune',
  },
  6: {
    id: 6,
    name: 'Water Essence',
    itemImage: '/images/runecrafting/water_talisman.png',
    class: 'rune',
  },
  7: {
    id: 7,
    name: 'Blood Essence',
    itemImage: '/images/runecrafting/blood_talisman.png',
    class: 'rune',
  },
  8: {
    id: 8,
    name: 'Death Essence',
    itemImage: '/images/runecrafting/death_talisman.png',
    class: 'rune',
  },
  9: {
    id: 9,
    name: 'Chaos Essence',
    itemImage: '/images/runecrafting/chaos_talisman.png',
    class: 'rune',
  },
  10: {
    id: 10,
    name: 'Nature Essence',
    itemImage: '/images/runecrafting/nature_talisman.png',
    class: 'rune',
  },
  11: {
    id: 11,
    name: 'Mind Essence',
    itemImage: '/images/runecrafting/mind_talisman.png',
    class: 'rune',
  },
  12: {
    id: 12,
    name: 'Cosmic Essence',
    itemImage: '/images/runecrafting/cosmic_talisman.png',
    class: 'rune',
  },
  50: {
    id: 50,
    name: 'Book',
    itemImage: '/images/misc/book.png',
    class: 'gem',
  },
  60: {
    id: 60,
    name: 'Raw Shrimp',
    itemImage: '/images/fishing/raw_shrimp.png',
    class: 'fish',
  },
  61: {
    id: 61,
    name: 'Raw Anchovy',
    itemImage: '/images/fishing/raw_anchovy.png',
    class: 'fish',
  },
  62: {
    id: 62,
    name: 'Raw Trout',
    itemImage: '/images/fishing/raw_trout.png',
    class: 'fish',
  },
  63: {
    id: 63,
    name: 'Raw Salmon',
    itemImage: '/images/fishing/raw_salmon.png',
    class: 'fish',
  },
  64: {
    id: 64,
    name: 'Raw Lobster',
    itemImage: '/images/fishing/raw_lobster.png',
    class: 'fish',
  },
  65: {
    id: 65,
    name: 'Raw Tuna',
    itemImage: '/images/fishing/raw_tuna.png',
    class: 'fish',
  },
  66: {
    id: 66,
    name: 'Raw Shark',
    itemImage: '/images/fishing/raw_shark.png',
    class: 'fish',
  },
  95: {
    id: 95,
    name: 'Burnt Fish',
    itemImage: '/images/cooking/burnt_fish.png',
    class: 'cookedFish',
  },
  96: {
    id: 96,
    name: 'Burnt Food',
    itemImage: '/images/cooking/burnt_food.png',
    class: 'cookedFish',
  },
  101: {
    id: 101,
    name: 'Copper Ore',
    itemImage: '/images/mining/copper_ore.png',
    class: 'ore',
  },
  102: {
    id: 102,
    name: 'Tin Ore',
    itemImage: '/images/mining/tin_ore.png',
    class: 'ore',
  },
  103: {
    id: 103,
    name: 'Iron Ore',
    itemImage: '/images/mining/iron_ore.png',
    class: 'ore',
  },
  104: {
    id: 104,
    name: 'Gold Ore',
    itemImage: '/images/mining/gold_ore.png',
    class: 'ore',
  },
  105: {
    id: 105,
    name: 'Mithril Ore',
    itemImage: '/images/mining/mithril_ore.png',
    class: 'ore',
  },
  106: {
    id: 106,
    name: 'Adamantite Ore',
    itemImage: '/images/mining/adamantite_ore.png',
    class: 'ore',
  },
  107: {
    id: 107,
    name: 'Runite Ore',
    itemImage: '/images/mining/runite_ore.png',
    class: 'ore',
  },
  108: {
    id: 108,
    name: 'Clay',
    itemImage: '/images/mining/clay.png',
    class: 'ore',
  },
  109: {
    id: 109,
    name: 'Stone',
    itemImage: '/images/mining/stone.png',
    class: 'ore',
  },
  110: {
    id: 110,
    name: 'Sand',
    itemImage: '/images/mining/sand.png',
    class: 'ore',
  },
  111: {
    id: 111,
    name: 'Silver',
    itemImage: '/images/mining/silver.png',
    class: 'ore',
  },
  112: {
    id: 112,
    name: 'Coal',
    itemImage: '/images/mining/coal.png',
    class: 'ore',
  },
  113: {
    id: 113,
    name: 'Rune Slate',
    itemImage: '/images/runecrafting/rune_slate.png',
    class: 'ore',
  },
  114: {
    id: 114,
    name: 'Stygian Ore',
    itemImage: '/images/mining/stygian_ore.png',
    class: 'ore',
  },
  150: {
    id: 150,
    name: 'Fertilizer',
    itemImage: '/images/farming/fertilizer.png',
    class: 'seed',
  },
  151: {
    id: 151,
    name: 'Carrot Seed',
    itemImage: '/images/farming/carrot_seed.png',
    class: 'seed',
  },
  152: {
    id: 152,
    name: 'Peppercorn Seed',
    itemImage: '/images/farming/peppercorn_seed.png',
    class: 'seed',
  },
  153: {
    id: 153,
    name: 'Sugarcane Seed',
    itemImage: '/images/farming/sugarcane_seed.png',
    class: 'seed',
  },
  154: {
    id: 154,
    name: 'Wheat Seed',
    itemImage: '/images/farming/wheat_seed.png',
    class: 'seed',
  },
  155: {
    id: 155,
    name: 'Potato Seed',
    itemImage: '/images/farming/potato_seed.png',
    class: 'seed',
  },
  156: {
    id: 156,
    name: 'Rice Seed',
    itemImage: '/images/farming/rice_seed.png',
    class: 'seed',
  },
  157: {
    id: 157,
    name: 'Tomato Seed',
    itemImage: '/images/farming/tomato_seed.png',
    class: 'seed',
  },
  158: {
    id: 158,
    name: 'Wildberry Bush Seed',
    itemImage: '/images/farming/wildberry_bush_seed.png',
    class: 'seed',
  },
  159: {
    id: 159,
    name: 'Chili Pepper Seed',
    itemImage: '/images/farming/chili_pepper_seed.png',
    class: 'seed',
  },
  160: {
    id: 160,
    name: 'Pumpkin Seed',
    itemImage: '/images/farming/pumpkin_seed.png',
    class: 'seed',
  },
  161: {
    id: 161,
    name: 'Mushroom Spore',
    itemImage: '/images/farming/mushroom_spore.png',
    class: 'seed',
  },
  170: {
    id: 170,
    name: 'Tree Seed',
    itemImage: '/images/farming/tree_seed.png',
    class: 'seed',
  },
  171: {
    id: 171,
    name: 'Oak Tree Seed',
    itemImage: '/images/farming/oak_tree_seed.png',
    class: 'seed',
  },
  172: {
    id: 172,
    name: 'Willow Tree Seed',
    itemImage: '/images/farming/willow_tree_seed.png',
    class: 'seed',
  },
  173: {
    id: 173,
    name: 'Maple Tree Seed',
    itemImage: '/images/farming/maple_tree_seed.png',
    class: 'seed',
  },
  174: {
    id: 174,
    name: 'Yew Tree Seed',
    itemImage: '/images/farming/yew_tree_seed.png',
    class: 'seed',
  },
  175: {
    id: 175,
    name: 'Banana Tree Seed',
    itemImage: '/images/farming/banana_tree_seed.png',
    class: 'seed',
  },
  176: {
    id: 176,
    name: 'Apple Tree Seed',
    itemImage: '/images/farming/apple_tree_seed.png',
    class: 'seed',
  },
  177: {
    id: 177,
    name: 'Elder Tree Seed',
    itemImage: '/images/farming/elder_tree_seed.png',
    class: 'seed',
  },
  180: {
    id: 180,
    name: 'Sageberry Bush Seed',
    itemImage: '/images/farming/sageberry_seed.png',
    class: 'seed',
  },
  185: {
    id: 185,
    name: 'Mysterious Seed',
    itemImage: '/images/farming/mysterious_seed.png',
    class: 'seed',
  },
  201: {
    id: 201,
    name: 'Bronze Bar',
    class: 'bar',
    itemImage: '/images/smithing/bronze_bar.png',
  },
  202: {
    id: 202,
    name: 'Iron Bar',
    class: 'bar',
    itemImage: '/images/smithing/iron_bar.png',
  },
  203: {
    id: 203,
    name: 'Gold Bar',
    class: 'bar',
    itemImage: '/images/smithing/gold_bar.png',
  },
  204: {
    id: 204,
    name: 'Mithril Bar',
    class: 'bar',
    itemImage: '/images/smithing/mithril_bar.png',
  },
  205: {
    id: 205,
    name: 'Adamantite Bar',
    class: 'bar',
    itemImage: '/images/smithing/adamantite_bar.png',
  },
  206: {
    id: 206,
    name: 'Runite Bar',
    class: 'bar',
    itemImage: '/images/smithing/runite_bar.png',
  },
  207: {
    id: 207,
    name: 'Stygian Bar',
    class: 'bar',
    itemImage: '/images/smithing/stygian_bar.png',
  },
  301: {
    id: 301,
    name: 'Branch',
    class: 'log',
    itemImage: '/images/foraging/branch.png',
  },
  302: {
    id: 302,
    name: 'Log',
    class: 'log',
    itemImage: '/images/foraging/log.png',
  },
  303: {
    id: 303,
    name: 'Oak Log',
    class: 'log',
    itemImage: '/images/foraging/oak_log.png',
  },
  304: {
    id: 304,
    name: 'Willow Log',
    class: 'log',
    itemImage: '/images/foraging/willow_log.png',
  },
  305: {
    id: 305,
    name: 'Maple Log',
    class: 'log',
    itemImage: '/images/foraging/maple_log.png',
  },
  306: {
    id: 306,
    name: 'Yew Log',
    class: 'log',
    itemImage: '/images/foraging/yew_log.png',
  },
  400: {
    id: 400,
    name: 'Sapphire',
    class: 'gem',
    itemImage: '/images/mining/sapphire.png',
  },
  401: {
    id: 401,
    name: 'Emerald',
    class: 'gem',
    itemImage: '/images/mining/emerald.png',
  },
  402: {
    id: 402,
    name: 'Ruby',
    class: 'gem',
    itemImage: '/images/mining/ruby.png',
  },
  403: {
    id: 403,
    name: 'Diamond',
    class: 'gem',
    itemImage: '/images/mining/diamond.png',
  },
  404: {
    id: 404,
    name: 'Black Opal',
    class: 'gem',
    itemImage: '/images/mining/black_opal.png',
  },
  500: {
    id: 500,
    name: 'Air Talisman',
    class: 'rune',
    itemImage: '/images/runecrafting/air_talisman.png',
  },
  501: {
    id: 501,
    name: 'Earth Talisman',
    class: 'rune',
    itemImage: '/images/runecrafting/earth_talisman.png',
  },
  502: {
    id: 502,
    name: 'Fire Talisman',
    class: 'rune',
    itemImage: '/images/runecrafting/fire_talisman.png',
  },
  503: {
    id: 503,
    name: 'Water Talisman',
    class: 'rune',
    itemImage: '/images/runecrafting/water_talisman.png',
  },
  504: {
    id: 504,
    name: 'Blood Talisman',
    class: 'rune',
    itemImage: '/images/runecrafting/blood_talisman.png',
  },
  505: {
    id: 505,
    name: 'Death Talisman',
    class: 'rune',
    itemImage: '/images/runecrafting/death_talisman.png',
  },
  506: {
    id: 506,
    name: 'Chaos Talisman',
    class: 'rune',
    itemImage: '/images/runecrafting/chaos_talisman.png',
  },
  507: {
    id: 507,
    name: 'Nature Talisman',
    class: 'rune',
    itemImage: '/images/runecrafting/nature_talisman.png',
  },
  508: {
    id: 508,
    name: 'Mind Talisman',
    class: 'rune',
    itemImage: '/images/runecrafting/mind_talisman.png',
  },
  509: {
    id: 509,
    name: 'Cosmic Talisman',
    class: 'rune',
    itemImage: '/images/runecrafting/cosmic_talisman.png',
  },
  510: {
    name: 'Air Rune',
    id: 510,
    class: 'rune',
    itemImage: '/images/runecrafting/air_rune.png',
  },
  511: {
    name: 'Earth Rune',
    id: 511,
    class: 'rune',
    itemImage: '/images/runecrafting/earth_rune.png',
  },
  512: {
    name: 'Fire Rune',
    id: 512,
    class: 'rune',
    itemImage: '/images/runecrafting/fire_rune.png',
  },
  513: {
    name: 'Water Rune',
    id: 513,
    class: 'rune',
    itemImage: '/images/runecrafting/water_rune.png',
  },
  514: {
    name: 'Blood Rune',
    id: 514,
    class: 'rune',
    itemImage: '/images/runecrafting/blood_rune.png',
  },
  515: {
    name: 'Death Rune',
    id: 515,
    class: 'rune',
    itemImage: '/images/runecrafting/death_rune.png',
  },
  516: {
    name: 'Chaos Rune',
    id: 516,
    class: 'rune',
    itemImage: '/images/runecrafting/chaos_rune.png',
  },
  517: {
    name: 'Nature Rune',
    id: 517,
    class: 'rune',
    itemImage: '/images/runecrafting/nature_rune.png',
  },
  518: {
    name: 'Mind Rune',
    id: 518,
    class: 'rune',
    itemImage: '/images/runecrafting/mind_rune.png',
  },
  519: {
    name: 'Cosmic Rune',
    id: 519,
    class: 'rune',
    itemImage: '/images/runecrafting/cosmic_rune.png',
  },
  600: {
    id: 600,
    name: 'Bronze Pickaxe',
    class: 'equipment',
    itemImage: '/images/mining/bronze_pickaxe.png',
  },
  601: {
    id: 601,
    name: 'Iron Pickaxe',
    class: 'equipment',
    itemImage: '/images/mining/iron_pickaxe.png',
  },
  602: {
    id: 602,
    name: 'Mithril Pickaxe',
    class: 'equipment',
    itemImage: '/images/mining/mithril_pickaxe.png',
  },
  603: {
    id: 603,
    name: 'Adamantite Pickaxe',
    class: 'equipment',
    itemImage: '/images/mining/adamantite_pickaxe.png',
  },
  604: {
    id: 604,
    name: 'Runite Pickaxe',
    class: 'equipment',
    itemImage: '/images/mining/rune_pickaxe.png',
  },
  605: {
    id: 605,
    name: 'Stygian Pickaxe',
    class: 'equipment',
    itemImage: '/images/mining/stygian_pickaxe.png',
  },
  610: {
    id: 610,
    name: 'Bronze Hatchet',
    class: 'equipment',
    itemImage: '/images/foraging/bronze_hatchet.png',
  },
  611: {
    id: 611,
    name: 'Iron Hatchet',
    class: 'equipment',
    itemImage: '/images/foraging/iron_hatchet.png',
  },
  612: {
    id: 612,
    name: 'Mithril Hatchet',
    class: 'equipment',
    itemImage: '/images/foraging/mithril_hatchet.png',
  },
  613: {
    id: 613,
    name: 'Adamantite Hatchet',
    class: 'equipment',
    itemImage: '/images/foraging/adamantite_hatchet.png',
  },
  614: {
    id: 614,
    name: 'Runite Hatchet',
    class: 'equipment',
    itemImage: '/images/foraging/rune_hatchet.png',
  },
  615: {
    id: 615,
    name: 'Stygian Hatchet',
    class: 'equipment',
    itemImage: '/images/foraging/stygian_hatchet.png',
  },
  620: {
    id: 620,
    name: 'Sapphire Ring',
    class: 'equipment',
    itemImage: '/images/jewellery/sapphire_ring.png',
  },
  621: {
    id: 621,
    name: 'Sapphire Necklace',
    class: 'equipment',
    itemImage: '/images/jewellery/sapphire_necklace.png',
  },
  622: {
    id: 622,
    name: 'Emerald Ring',
    class: 'equipment',
    itemImage: '/images/jewellery/emerald_ring.png',
  },
  623: {
    id: 623,
    name: 'Emerald Necklace',
    class: 'equipment',
    itemImage: '/images/jewellery/emerald_necklace.png',
  },
  624: {
    id: 624,
    name: 'Ruby Ring',
    class: 'equipment',
    itemImage: '/images/jewellery/ruby_ring.png',
  },
  625: {
    id: 625,
    name: 'Ruby Necklace',
    class: 'equipment',
    itemImage: '/images/jewellery/ruby_necklace.png',
  },
  626: {
    id: 626,
    name: 'Diamond Ring',
    class: 'equipment',
    itemImage: '/images/jewellery/diamond_ring.png',
  },
  627: {
    id: 627,
    name: 'Diamond Necklace',
    class: 'equipment',
    itemImage: '/images/jewellery/diamond_necklace.png',
  },
  628: {
    id: 628,
    name: 'Prismatic Necklace',
    class: 'equipment',
    itemImage: '/images/jewellery/prismatic_necklace.png',
  },
  629: {
    id: 629,
    name: 'Prismatic Ring',
    class: 'equipment',
    itemImage: '/images/jewellery/prismatic_ring.png',
  },
  630: {
    id: 630,
    name: 'Black Opal Ring',
    class: 'equipment',
    itemImage: '/images/jewellery/black_opal_ring.png',
  },
  631: {
    id: 631,
    name: 'Black Opal Necklace',
    class: 'equipment',
    itemImage: '/images/jewellery/black_opal_necklace.png',
  },
  640: {
    id: 640,
    name: 'Gold Ring',
    class: 'equipment',
    itemImage: '/images/jewellery/gold_ring.png',
  },
  641: {
    id: 641,
    name: 'Gold Necklace',
    class: 'equipment',
    itemImage: '/images/jewellery/gold_necklace.png',
  },
  660: {
    id: 660,
    name: 'Bronze Hoe',
    class: 'equipment',
    itemImage: '/images/farming/bronze_hoe.png',
  },
  661: {
    id: 661,
    name: 'Iron Hoe',
    class: 'equipment',
    itemImage: '/images/farming/iron_hoe.png',
  },
  662: {
    id: 662,
    name: 'Mithril Hoe',
    class: 'equipment',
    itemImage: '/images/farming/mithril_hoe.png',
  },
  663: {
    id: 663,
    name: 'Adamantite Hoe',
    class: 'equipment',
    itemImage: '/images/farming/adamantite_hoe.png',
  },
  664: {
    id: 664,
    name: 'Runite Hoe',
    class: 'equipment',
    itemImage: '/images/farming/runite_hoe.png',
  },
  665: {
    id: 665,
    name: 'Stygian Hoe',
    class: 'equipment',
    itemImage: '/images/farming/stygian_hoe.png',
  },
  690: {
    id: 690,
    name: 'Fishing Net',
    class: 'fish',
    itemImage: '/images/fishing/net.png',
  },
  691: {
    id: 691,
    name: 'Fly Fishing Rod',
    class: 'fish',
    itemImage: '/images/fishing/fishing_rod.png',
  },
  692: {
    id: 692,
    name: 'Cage',
    class: 'fish',
    itemImage: '/images/fishing/fishing_cage_2.png',
  },
  693: {
    id: 693,
    name: 'Harpoon',
    class: 'fish',
    itemImage: '/images/fishing/harpoon.png',
  },
  700: {
    id: 700,
    name: 'Feather',
    class: 'fish',
    itemImage: '/images/fishing/feather.png',
  },
  701: {
    id: 701,
    name: 'Fish Oil',
    class: 'cookedFish',
    itemImage: '/images/cooking/fish_oil.png',
  },
  702: {
    id: 702,
    name: 'Pyre Log',
    class: 'log',
    itemImage: '/images/foraging/pyre.png',
  },
  703: {
    id: 703,
    name: 'Pyre Oak Log',
    class: 'log',
    itemImage: '/images/foraging/oak_pyre.png',
  },
  704: {
    id: 704,
    name: 'Pyre Willow Log',
    class: 'log',
    itemImage: '/images/foraging/willow_pyre.png',
  },
  705: {
    id: 705,
    name: 'Pyre Maple Log',
    class: 'log',
    itemImage: '/images/foraging/maple_pyre.png',
  },
  706: {
    id: 706,
    name: 'Pyre Yew Log',
    class: 'log',
    itemImage: '/images/foraging/yew_pyre.png',
  },
  800: {
    id: 800,
    name: 'Ichor',
    class: 'bar',
    itemImage: '/images/smithing/ichor.png',
  },
  900: {
    name: 'Geode',
    id: 900,
    class: 'gem',
    itemImage: '/images/misc/geode.png',
  },
  901: {
    name: "Bird's Nest",
    id: 901,
    class: 'gem',
    itemImage: '/images/misc/bird_nest.png',
  },
  902: {
    name: 'Sunken Treasure',
    id: 902,
    class: 'gem',
    itemImage: '/images/misc/sunken_treasure.png',
  },
  903: {
    name: 'Satchel',
    id: 903,
    class: 'gem',
    itemImage: '/images/misc/satchel.png',
  },
  1e3: {
    name: 'Bronze Scimitar',
    id: 1e3,
    class: 'equipment',
    itemImage: '/images/combat/equipment/bronze_scimitar.png',
  },
  1001: {
    name: 'Bronze Battleaxe',
    id: 1001,
    class: 'equipment',
    itemImage: '/images/combat/equipment/bronze_battleaxe.png',
  },
  1002: {
    name: 'Bronze Daggers',
    id: 1002,
    class: 'equipment',
    itemImage: '/images/combat/equipment/bronze_dagger.png',
  },
  1003: {
    name: 'Bronze Greatsword',
    id: 1003,
    class: 'equipment',
    itemImage: '/images/combat/equipment/bronze_2h_sword.png',
  },
  1004: {
    name: 'Iron Scimitar',
    id: 1004,
    class: 'equipment',
    itemImage: '/images/combat/equipment/iron_scimitar.png',
  },
  1005: {
    name: 'Iron Battleaxe',
    id: 1005,
    class: 'equipment',
    itemImage: '/images/combat/equipment/iron_battleaxe.png',
  },
  1006: {
    name: 'Iron Daggers',
    id: 1006,
    class: 'equipment',
    itemImage: '/images/combat/equipment/iron_dagger.png',
  },
  1007: {
    name: 'Iron Greatsword',
    id: 1007,
    class: 'equipment',
    itemImage: '/images/combat/equipment/iron_2h_sword.png',
  },
  1008: {
    name: 'Obsidian Scimitar',
    id: 1008,
    class: 'equipment',
    itemImage: '/images/combat/equipment/black_scimitar.png',
  },
  1009: {
    name: 'Obsidian Battleaxe',
    id: 1009,
    class: 'equipment',
    itemImage: '/images/combat/equipment/black_battleaxe.png',
  },
  1010: {
    name: 'Obsidian Daggers',
    id: 1010,
    class: 'equipment',
    itemImage: '/images/combat/equipment/black_dagger.png',
  },
  1011: {
    name: 'Obsidian Greatsword',
    id: 1011,
    class: 'equipment',
    itemImage: '/images/combat/equipment/black_2h_sword.png',
  },
  1012: {
    name: 'Mithril Scimitar',
    id: 1012,
    class: 'equipment',
    itemImage: '/images/combat/equipment/mithril_scimitar.png',
  },
  1013: {
    name: 'Mithril Battleaxe',
    id: 1013,
    class: 'equipment',
    itemImage: '/images/combat/equipment/mithril_battleaxe.png',
  },
  1014: {
    name: 'Mithril Daggers',
    id: 1014,
    class: 'equipment',
    itemImage: '/images/combat/equipment/mithril_dagger.png',
  },
  1015: {
    name: 'Mithril Greatsword',
    id: 1015,
    class: 'equipment',
    itemImage: '/images/combat/equipment/mithril_2h_sword.png',
  },
  1016: {
    name: 'Adamantite Scimitar',
    id: 1016,
    class: 'equipment',
    itemImage: '/images/combat/equipment/adamantite_scimitar.png',
  },
  1017: {
    name: 'Adamantite Battleaxe',
    id: 1017,
    class: 'equipment',
    itemImage: '/images/combat/equipment/adamantite_battleaxe.png',
  },
  1018: {
    name: 'Adamantite Daggers',
    id: 1018,
    class: 'equipment',
    itemImage: '/images/combat/equipment/adamantite_dagger.png',
  },
  1019: {
    name: 'Adamantite Greatsword',
    id: 1019,
    class: 'equipment',
    itemImage: '/images/combat/equipment/adamantite_2h_sword.png',
  },
  1020: {
    name: 'Runite Scimitar',
    id: 1020,
    class: 'equipment',
    itemImage: '/images/combat/equipment/rune_scimitar.png',
  },
  1021: {
    name: 'Runite Battleaxe',
    id: 1021,
    class: 'equipment',
    itemImage: '/images/combat/equipment/rune_battleaxe.png',
  },
  1022: {
    name: 'Runite Daggers',
    id: 1022,
    class: 'equipment',
    itemImage: '/images/combat/equipment/rune_dagger.png',
  },
  1023: {
    name: 'Runite Greatsword',
    id: 1023,
    class: 'equipment',
    itemImage: '/images/combat/equipment/rune_2h_sword.png',
  },
  1024: {
    name: 'Stygian Scimitar',
    id: 1024,
    class: 'equipment',
    itemImage: '/images/combat/equipment/stygian_scimitar.png',
  },
  1025: {
    name: 'Stygian Battleaxe',
    id: 1025,
    class: 'equipment',
    itemImage: '/images/combat/equipment/stygian_battleaxe.png',
  },
  1026: {
    name: 'Stygian Daggers',
    id: 1026,
    class: 'equipment',
    itemImage: '/images/combat/equipment/stygian_dagger.png',
  },
  1027: {
    name: 'Stygian Greatsword',
    id: 1027,
    class: 'equipment',
    itemImage: '/images/combat/equipment/stygian_2h_sword.png',
  },
  1050: {
    name: 'Bronze Helm',
    id: 1050,
    class: 'equipment',
    itemImage: '/images/combat/equipment/bronze_med_helm.png',
  },
  1051: {
    name: 'Iron Helm',
    id: 1051,
    class: 'equipment',
    itemImage: '/images/combat/equipment/iron_med_helm.png',
  },
  1052: {
    name: 'Obsidian Helm',
    id: 1052,
    class: 'equipment',
    itemImage: '/images/combat/equipment/black_med_helm.png',
  },
  1053: {
    name: 'Mithril Helm',
    id: 1053,
    class: 'equipment',
    itemImage: '/images/combat/equipment/mithril_med_helm.png',
  },
  1054: {
    name: 'Adamantite Helm',
    id: 1054,
    class: 'equipment',
    itemImage: '/images/combat/equipment/adamantite_med_helm.png',
  },
  1055: {
    name: 'Runite Helm',
    id: 1055,
    class: 'equipment',
    itemImage: '/images/combat/equipment/rune_med_helm.png',
  },
  1056: {
    name: 'Stygian Helm',
    id: 1056,
    class: 'equipment',
    itemImage: '/images/combat/equipment/stygian_med_helm.png',
  },
  1060: {
    name: 'Bronze Full Helm',
    id: 1060,
    class: 'equipment',
    itemImage: '/images/combat/equipment/bronze_full_helm.png',
  },
  1061: {
    name: 'Iron Full Helm',
    id: 1061,
    class: 'equipment',
    itemImage: '/images/combat/equipment/iron_full_helm.png',
  },
  1062: {
    name: 'Obsidian Full Helm',
    id: 1062,
    class: 'equipment',
    itemImage: '/images/combat/equipment/black_full_helm.png',
  },
  1063: {
    name: 'Mithril Full Helm',
    id: 1063,
    class: 'equipment',
    itemImage: '/images/combat/equipment/mithril_full_helm.png',
  },
  1064: {
    name: 'Adamantite Full Helm',
    id: 1064,
    class: 'equipment',
    itemImage: '/images/combat/equipment/adamantite_full_helm.png',
  },
  1065: {
    name: 'Runite Full Helm',
    id: 1065,
    class: 'equipment',
    itemImage: '/images/combat/equipment/rune_full_helm.png',
  },
  1066: {
    name: 'Stygian Full Helm',
    id: 1066,
    class: 'equipment',
    itemImage: '/images/combat/equipment/stygian_full_helm.png',
  },
  1070: {
    name: 'Bronze Shield',
    id: 1070,
    class: 'equipment',
    itemImage: '/images/combat/equipment/bronze_shield.png',
  },
  1071: {
    name: 'Iron Shield',
    id: 1071,
    class: 'equipment',
    itemImage: '/images/combat/equipment/iron_shield.png',
  },
  1072: {
    name: 'Obsidian Shield',
    id: 1072,
    class: 'equipment',
    itemImage: '/images/combat/equipment/black_shield.png',
  },
  1073: {
    name: 'Mithril Shield',
    id: 1073,
    class: 'equipment',
    itemImage: '/images/combat/equipment/mithril_shield.png',
  },
  1074: {
    name: 'Adamantite Shield',
    id: 1074,
    class: 'equipment',
    itemImage: '/images/combat/equipment/adamantite_shield.png',
  },
  1075: {
    name: 'Runite Shield',
    id: 1075,
    class: 'equipment',
    itemImage: '/images/combat/equipment/rune_shield.png',
  },
  1076: {
    name: 'Stygian Shield',
    id: 1076,
    class: 'equipment',
    itemImage: '/images/combat/equipment/stygian_shield.png',
  },
  1090: {
    name: 'Bronze Breastplate',
    id: 1090,
    class: 'equipment',
    itemImage: '/images/combat/equipment/bronze_platebody.png',
  },
  1091: {
    name: 'Bronze Chainmail',
    id: 1091,
    class: 'equipment',
    itemImage: '/images/combat/equipment/bronze_chainbody.png',
  },
  1092: {
    name: 'Iron Breastplate',
    id: 1092,
    class: 'equipment',
    itemImage: '/images/combat/equipment/iron_platebody.png',
  },
  1093: {
    name: 'Iron Chainmail',
    id: 1093,
    class: 'equipment',
    itemImage: '/images/combat/equipment/iron_chainbody.png',
  },
  1094: {
    name: 'Obsidian Breastplate',
    id: 1094,
    class: 'equipment',
    itemImage: '/images/combat/equipment/black_platebody.png',
  },
  1095: {
    name: 'Obsidian Chainmail',
    id: 1095,
    class: 'equipment',
    itemImage: '/images/combat/equipment/black_chainbody.png',
  },
  1096: {
    name: 'Mithril Breastplate',
    id: 1096,
    class: 'equipment',
    itemImage: '/images/combat/equipment/mithril_platebody.png',
  },
  1097: {
    name: 'Mithril Chainmail',
    id: 1097,
    class: 'equipment',
    itemImage: '/images/combat/equipment/mithril_chainbody.png',
  },
  1098: {
    name: 'Adamantite Breastplate',
    id: 1098,
    class: 'equipment',
    itemImage: '/images/combat/equipment/adamantite_platebody.png',
  },
  1099: {
    name: 'Adamantite Chainmail',
    id: 1099,
    class: 'equipment',
    itemImage: '/images/combat/equipment/adamantite_chainbody.png',
  },
  1100: {
    name: 'Runite Breastplate',
    id: 1100,
    class: 'equipment',
    itemImage: '/images/combat/equipment/rune_platebody.png',
  },
  1101: {
    name: 'Runite Chainmail',
    id: 1101,
    class: 'equipment',
    itemImage: '/images/combat/equipment/rune_chainbody.png',
  },
  1102: {
    name: 'Stygian Breastplate',
    id: 1102,
    class: 'equipment',
    itemImage: '/images/combat/equipment/stygian_platebody.png',
  },
  1103: {
    name: 'Stygian Chainmail',
    id: 1103,
    class: 'equipment',
    itemImage: '/images/combat/equipment/stygian_chainbody.png',
  },
  1110: {
    name: 'Bronze Plate Leggings',
    id: 1110,
    class: 'equipment',
    itemImage: '/images/combat/equipment/bronze_platelegs.png',
  },
  1111: {
    name: 'Iron Plate Leggings',
    id: 1111,
    class: 'equipment',
    itemImage: '/images/combat/equipment/iron_platelegs.png',
  },
  1112: {
    name: 'Obsidian Plate Leggings',
    id: 1112,
    class: 'equipment',
    itemImage: '/images/combat/equipment/black_platelegs.png',
  },
  1113: {
    name: 'Mithril Plate Leggings',
    id: 1113,
    class: 'equipment',
    itemImage: '/images/combat/equipment/mithril_platelegs.png',
  },
  1114: {
    name: 'Adamantite Plate Leggings',
    id: 1114,
    class: 'equipment',
    itemImage: '/images/combat/equipment/adamantite_platelegs.png',
  },
  1115: {
    name: 'Runite Plate Leggings',
    id: 1115,
    class: 'equipment',
    itemImage: '/images/combat/equipment/rune_platelegs.png',
  },
  1116: {
    name: 'Stygian Plate Leggings',
    id: 1116,
    class: 'equipment',
    itemImage: '/images/combat/equipment/stygian_platelegs.png',
  },
  1130: {
    name: 'Bronze Boots',
    id: 1130,
    class: 'equipment',
    itemImage: '/images/combat/equipment/bronze_boots.png',
  },
  1131: {
    name: 'Iron Boots',
    id: 1131,
    class: 'equipment',
    itemImage: '/images/combat/equipment/iron_boots.png',
  },
  1132: {
    name: 'Obsidian Boots',
    id: 1132,
    class: 'equipment',
    itemImage: '/images/combat/equipment/black_boots.png',
  },
  1133: {
    name: 'Mithril Boots',
    id: 1133,
    class: 'equipment',
    itemImage: '/images/combat/equipment/mithril_boots.png',
  },
  1134: {
    name: 'Adamantite Boots',
    id: 1134,
    class: 'equipment',
    itemImage: '/images/combat/equipment/adamantite_boots.png',
  },
  1135: {
    name: 'Runite Boots',
    id: 1135,
    class: 'equipment',
    itemImage: '/images/combat/equipment/rune_boots.png',
  },
  1136: {
    name: 'Stygian Boots',
    id: 1136,
    class: 'equipment',
    itemImage: '/images/combat/equipment/stygian_boots.png',
  },
  1150: {
    name: 'Bronze Gloves',
    id: 1150,
    class: 'equipment',
    itemImage: '/images/combat/equipment/bronze_gloves.png',
  },
  1151: {
    name: 'Iron Gloves',
    id: 1151,
    class: 'equipment',
    itemImage: '/images/combat/equipment/iron_gloves.png',
  },
  1152: {
    name: 'Obsidian Gloves',
    id: 1152,
    class: 'equipment',
    itemImage: '/images/combat/equipment/black_gloves.png',
  },
  1153: {
    name: 'Mithril Gloves',
    id: 1153,
    class: 'equipment',
    itemImage: '/images/combat/equipment/mithril_gloves.png',
  },
  1154: {
    name: 'Adamantite Gloves',
    id: 1154,
    class: 'equipment',
    itemImage: '/images/combat/equipment/adamantite_gloves.png',
  },
  1155: {
    name: 'Runite Gloves',
    id: 1155,
    class: 'equipment',
    itemImage: '/images/combat/equipment/rune_gloves.png',
  },
  1156: {
    name: 'Stygian Gloves',
    id: 1156,
    class: 'equipment',
    itemImage: '/images/combat/equipment/stygian_gloves.png',
  },
  1500: {
    name: 'Santa Hat',
    id: 1500,
    class: 'equipment',
    itemImage: '/images/combat/equipment/santa_hat.png',
  },
  1501: {
    name: 'Snowman Head',
    id: 1501,
    class: 'equipment',
    itemImage: '/images/combat/equipment/snowman_head.png',
  },
  1502: {
    name: 'Tophat',
    id: 1502,
    class: 'equipment',
    itemImage: '/images/combat/equipment/tophat.png',
  },
  1503: {
    name: 'Lesser Ladle',
    id: 1503,
    class: 'equipment',
    itemImage: '/images/combat/equipment/lesser_ladle.png',
  },
  1504: {
    name: 'Ladle',
    id: 1504,
    class: 'equipment',
    itemImage: '/images/combat/equipment/ladle.png',
  },
  1505: {
    name: 'Greater Ladle',
    id: 1505,
    class: 'equipment',
    itemImage: '/images/combat/equipment/greater_ladle.png',
  },
  1506: {
    name: 'Moss Maul',
    id: 1506,
    class: 'equipment',
    itemImage: '/images/combat/equipment/moss_maul.png',
  },
  1507: {
    name: 'Modified Diving Gloves',
    id: 1507,
    class: 'equipment',
    itemImage: '/images/combat/equipment/modified_diving_gloves.png',
  },
  1508: {
    name: "King's Crown",
    id: 1508,
    class: 'equipment',
    itemImage: '/images/combat/equipment/kings_crown.png',
  },
  1509: {
    name: 'Fire Orb',
    id: 1509,
    class: 'equipment',
    itemImage: '/images/combat/equipment/fire_orb.png',
  },
  1510: {
    id: 1510,
    name: 'Kalanahmatti',
    class: 'bar',
    itemImage: '/images/combat/equipment/kalanahmatti.png',
  },
  1511: {
    name: 'Shard of Kalanahmatti',
    id: 1511,
    class: 'equipment',
    itemImage: '/images/combat/equipment/shard_of_kalanahmatti.png',
  },
  1512: {
    name: 'Zero Edge',
    id: 1512,
    class: 'equipment',
    itemImage: '/images/combat/equipment/zero_edge.png',
  },
  1513: {
    name: 'Crest of Chaos',
    id: 1513,
    class: 'equipment',
    itemImage: '/images/combat/equipment/crest_of_chaos.png',
  },
  1514: {
    name: 'Forgotten Soul',
    id: 1514,
    class: 'equipment',
    itemImage: '/images/combat/equipment/forgotten-soul-axe.png',
  },
  1515: {
    name: 'Forgotten Soul',
    id: 1515,
    class: 'equipment',
    itemImage: '/images/combat/equipment/forgotten-soul-scimitar.png',
  },
  1516: {
    name: 'Forgotten Soul',
    id: 1516,
    class: 'equipment',
    itemImage: '/images/combat/equipment/forgotten-soul-two-handed.png',
  },
  1517: {
    name: 'Gargoyle Chainmail',
    id: 1517,
    class: 'equipment',
    itemImage: '/images/combat/equipment/gargoyle_chain.png',
  },
  1518: {
    name: 'Gargoyle Legs',
    id: 1518,
    class: 'equipment',
    itemImage: '/images/combat/equipment/gargoyle_pants.png',
  },
  1519: {
    name: 'Gargoyle Boots',
    id: 1519,
    class: 'equipment',
    itemImage: '/images/combat/equipment/gargoyle_boots.png',
  },
  1520: {
    name: 'Gargoyle Helm',
    id: 1520,
    class: 'equipment',
    itemImage: '/images/combat/equipment/gargoyle_helm.png',
  },
  1521: {
    name: 'Gargoyle Shield',
    id: 1521,
    class: 'equipment',
    itemImage: '/images/combat/equipment/gargoyle_shield.png',
  },
  1522: {
    name: 'Gargoyle Falchion',
    id: 1522,
    class: 'equipment',
    itemImage: '/images/combat/equipment/gargoyle_falchion.png',
  },
  1523: {
    name: 'Gargoyle Daggers',
    id: 1523,
    class: 'equipment',
    itemImage: '/images/combat/equipment/dagger_gargoyle.png',
  },
  1524: {
    name: 'Gargoyle Glaive',
    id: 1524,
    class: 'equipment',
    itemImage: '/images/combat/equipment/gargoyle_glaive.png',
  },
  1525: {
    name: 'Infernal Lance',
    id: 1525,
    class: 'equipment',
    itemImage: '/images/combat/equipment/infernal_lance.png',
  },
  1526: {
    name: 'Black Knight Great Helm',
    id: 1526,
    class: 'equipment',
    itemImage: '/images/combat/equipment/black_black_knight_great_helm.png',
  },
  1530: {
    name: 'Mysterious Man',
    id: 1530,
    class: 'equipment',
    itemImage: '/images/combat/equipment/hatcontest_mysterious_man.png',
  },
  1531: {
    name: 'Corny Joke',
    id: 1531,
    class: 'equipment',
    itemImage: '/images/combat/equipment/hatcontest_cornyjoke.png',
  },
  1532: {
    name: 'Death Metal Wig',
    id: 1532,
    class: 'equipment',
    itemImage: '/images/combat/equipment/hatcontest_death_metal_wig.png',
  },
  1540: {
    name: 'Shrimp Carapace',
    id: 1540,
    class: 'equipment',
    itemImage: '/images/combat/equipment/shrimp_armor.png',
  },
  1541: {
    name: 'Shrimp Greaves',
    id: 1541,
    class: 'equipment',
    itemImage: '/images/combat/equipment/shrimp_pants.png',
  },
  1542: {
    name: 'Shrimp Helm',
    id: 1542,
    class: 'equipment',
    itemImage: '/images/combat/equipment/shrimp_helm.png',
  },
  1543: {
    name: 'Shrimp Shell',
    id: 1543,
    class: 'equipment',
    itemImage: '/images/combat/equipment/shrimp_shield.png',
  },
  1600: {
    name: 'Scroll',
    id: 1600,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll.png',
  },
  1601: {
    name: 'Scroll of Embers',
    id: 1601,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_embers.png',
  },
  1602: {
    name: 'Scroll of the Prospector',
    id: 1602,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_the_prospector.png',
  },
  1603: {
    name: 'Scroll of the Scholar',
    id: 1603,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_the_scholar.png',
  },
  1604: {
    name: 'Scroll of Gathering',
    id: 1604,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_gathering.png',
  },
  1605: {
    name: 'Scroll of Superheating',
    id: 1605,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_superheating.png',
  },
  1606: {
    name: 'Scroll of Pyromancy',
    id: 1606,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_pyromancy.png',
  },
  1607: {
    name: 'Scroll of Wealth',
    id: 1607,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_wealth.png',
  },
  1608: {
    name: 'Scroll of Haste',
    id: 1608,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_haste.png',
  },
  1609: {
    name: 'Scroll of Naturalist',
    id: 1609,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_naturalist_v2.png',
  },
  1610: {
    name: 'Scroll of Acrobatics',
    id: 1610,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_naturalist_v2.png',
  },
  1611: {
    name: 'Scroll of Critical Strike',
    id: 1611,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_critical_strike.png',
  },
  1612: {
    name: 'Scroll of Poisoning',
    id: 1612,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_naturalist_v2.png',
  },
  1613: {
    name: 'Scroll of Accuracy',
    id: 1613,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_critical_strike.png',
  },
  1614: {
    name: 'Scroll of Deflect',
    id: 1614,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_naturalist_v2.png',
  },
  1615: {
    name: 'Scroll of Force',
    id: 1615,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_force.png',
  },
  1616: {
    name: 'Scroll of Healing',
    id: 1616,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_healing.png',
  },
  1617: {
    name: 'Scroll of Weakening',
    id: 1617,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_weakening.png',
  },
  1618: {
    name: 'Scroll of Reinforcement',
    id: 1618,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_reinforcement.png',
  },
  1619: {
    name: 'Scroll of Protection',
    id: 1619,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_reinforcement.png',
  },
  1620: {
    name: 'Scroll of Counterattack',
    id: 1620,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_naturalist_v2.png',
  },
  1621: {
    name: 'Scroll of Recklessness',
    id: 1621,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_recklessness.png',
  },
  1622: {
    name: 'Scroll of Efficiency',
    id: 1622,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_efficiency.png',
  },
  1623: {
    name: 'Scroll of Fishing',
    id: 1623,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_fishing.png',
  },
  1624: {
    name: 'Scroll of Cooking',
    id: 1624,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_cooking.png',
  },
  1625: {
    name: 'Scroll of Crafting',
    id: 1625,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_efficiency.png',
  },
  1626: {
    name: 'Scroll of Refining',
    id: 1626,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_refining.png',
  },
  1627: {
    name: 'Scroll of Runecrafting',
    id: 1627,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_runecrafting.png',
  },
  1628: {
    name: 'Scroll of Chances',
    id: 1628,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_chances.png',
  },
  1629: {
    name: 'Scroll of the Shrimp Lord',
    id: 1629,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_the_shrimp_lord.png',
  },
  1630: {
    name: 'Scroll of Enlightenment',
    id: 1630,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_enlightment.png',
  },
  1631: {
    name: 'Scroll of Prolonging',
    id: 1631,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_boosting.png',
  },
  1632: {
    name: 'Scroll of the Treasure Hunter',
    id: 1632,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_treasure_hunter.png',
  },
  1633: {
    name: 'Scroll of Inferno',
    id: 1633,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_inferno.png',
  },
  1634: {
    name: 'Scroll of Destructive Testing',
    id: 1634,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_destructive_testing.png',
  },
  1635: {
    name: 'Scroll of Nature',
    id: 1635,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_the_nature.png',
  },
  1636: {
    name: 'Scroll of Root Digging',
    id: 1636,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_root_digging.png',
  },
  1637: {
    name: 'Scroll of Patience',
    id: 1637,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_patience.png',
  },
  1638: {
    name: 'Scroll of Overhealing',
    id: 1638,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_of_overhealing.png',
  },
  1639: {
    name: 'Scroll of Farming',
    id: 1639,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_farming.png',
  },
  1640: {
    name: 'Scroll of the Gold Digger',
    id: 1640,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_golddigger.png',
  },
  1641: {
    name: 'Scroll of Fertilizing',
    id: 1641,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_fertilizing.png',
  },
  1642: {
    name: 'Scroll of Cultivation',
    id: 1642,
    class: 'enchanted-scroll',
    itemImage: '/images/enchanting/scroll_cultivation.png',
  },
  2e3: {
    name: 'Raw Chicken',
    id: 2e3,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/raw_chicken.png',
  },
  2001: {
    name: 'Raw Beef',
    id: 2001,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/raw_beef.png',
  },
  2009: {
    name: 'Spider Legs',
    id: 2009,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/spider_legs.png',
  },
  2010: {
    name: 'Goblin Brain',
    id: 2010,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/goblin_brain.png',
  },
  2012: {
    name: 'Pepper',
    id: 2012,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/pepper.png',
  },
  2013: {
    name: 'Salt',
    id: 2013,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/salt.png',
  },
  2014: {
    name: 'Ashes',
    id: 2014,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/ashes.png',
  },
  2015: {
    name: 'Sugar',
    id: 2015,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/sugar.png',
  },
  2016: {
    name: 'Honey',
    id: 2016,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/honey.png',
  },
  2017: {
    name: 'Milk',
    id: 2017,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/milk.png',
  },
  2018: {
    name: 'Butter',
    id: 2018,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/butter.png',
  },
  2019: {
    name: 'Egg',
    id: 2019,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/egg.png',
  },
  2020: {
    name: 'Mushroom',
    id: 2020,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/mushroom.png',
  },
  2021: {
    name: 'Carrot',
    id: 2021,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/carrot.png',
  },
  2022: {
    name: 'Chili Pepper',
    id: 2022,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/chili_pepper.png',
  },
  2023: {
    name: 'Potato',
    id: 2023,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/potato.png',
  },
  2024: {
    name: 'Pumpkin',
    id: 2024,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/pumpkin.png',
  },
  2025: {
    name: 'Tomato',
    id: 2025,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/tomato.png',
  },
  2026: {
    name: 'Apple',
    id: 2026,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/apple.png',
  },
  2027: {
    name: 'Wildberry',
    id: 2027,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/wildberry.png',
  },
  2028: {
    name: 'Banana',
    id: 2028,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/banana.png',
  },
  2029: {
    name: 'Wheat',
    id: 2029,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/wheat.png',
  },
  2030: {
    name: 'Rice',
    id: 2030,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/rice.png',
  },
  2031: {
    name: 'Sageberry',
    id: 2031,
    class: 'cooking-ingredient',
    itemImage: '/images/farming/sage_berry.png',
  },
  2100: {
    name: 'Questionable Food',
    id: 2100,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/questionable_food.png',
  },
  2101: {
    name: 'Monster Surprise',
    id: 2101,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/monster_surprise.png',
  },
  2102: {
    name: 'Seared Steak',
    id: 2102,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/seared_steak.png',
  },
  2103: {
    name: 'Seared Fish',
    id: 2103,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/seared_fish.png',
  },
  2104: {
    name: 'Seared Poultry',
    id: 2104,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/seared_bird.png',
  },
  2105: {
    name: 'Birdie Pasta',
    id: 2105,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/birdie_pasta.png',
  },
  2106: {
    name: 'Spaghetti & Meat',
    id: 2106,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/spaghetti_meat.png',
  },
  2107: {
    name: 'Sushi',
    id: 2107,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/sushi.png',
  },
  2108: {
    name: 'Birdie Pie',
    id: 2108,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/birdie_pie.png',
  },
  2109: {
    name: 'Cottage Pie',
    id: 2109,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/cottage_pie.png',
  },
  2110: {
    name: "Fisherman's Pie",
    id: 2110,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/fisherman_pie.png',
  },
  2111: {
    name: 'Fruit Pie',
    id: 2111,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/fruit_pie.png',
  },
  2112: {
    name: 'Demon Cake',
    id: 2112,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/demon_cake.png',
  },
  2113: {
    name: 'Cake',
    id: 2113,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/cake.png',
  },
  2114: {
    name: 'Fruit Cake',
    id: 2114,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/fruit_cake.png',
  },
  2115: {
    name: 'Grain Cake',
    id: 2115,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/grain_cake.png',
  },
  2116: {
    name: 'Omelette',
    id: 2116,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/omelette.png',
  },
  2117: {
    name: 'Monster Omelette',
    id: 2117,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/monster_omelette.png',
  },
  2118: {
    name: 'Meaty Omelette',
    id: 2118,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/meat_omelette.png',
  },
  2119: {
    name: 'Veggie Crepe',
    id: 2119,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/veggie_crepe.png',
  },
  2120: {
    name: 'Fruity Crepe',
    id: 2120,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/fruit_crepe.png',
  },
  2121: {
    name: 'Eggnog',
    id: 2121,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/egg_nog.png',
  },
  2122: {
    name: 'Meat Roast',
    id: 2122,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/meat_roast.png',
  },
  2123: {
    name: 'Fried Fruit',
    id: 2123,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/fried_fruit.png',
  },
  2124: {
    name: 'Grilled Veggies',
    id: 2124,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/grilled_veggies.png',
  },
  2125: {
    name: 'Kebabs',
    id: 2125,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/kababs.png',
  },
  2126: {
    name: 'Candied Fruit',
    id: 2126,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/candied_fruit.png',
  },
  2127: {
    name: 'Milkshake',
    id: 2127,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/milkshake.png',
  },
  2128: {
    name: 'Vegetable Stew',
    id: 2128,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/veggie_stew.png',
  },
  2129: {
    name: 'Meaty Stew',
    id: 2129,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/meaty_stew.png',
  },
  2130: {
    name: 'Monster Stew',
    id: 2130,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/monster_stew.png',
  },
  2131: {
    name: 'Jerky',
    id: 2131,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/jerky.png',
  },
  2132: {
    name: 'Pudding',
    id: 2132,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/pudding.png',
  },
  2133: {
    name: 'Ice Cream',
    id: 2133,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/icecream.png',
  },
  2134: {
    name: 'Monster Curry',
    id: 2134,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/monster_curry.png',
  },
  2135: {
    name: 'Birdie Curry',
    id: 2135,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/birdie_curry.png',
  },
  2136: {
    name: 'Beast Curry',
    id: 2136,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/beast_curry.png',
  },
  2137: {
    name: 'Seafood Curry',
    id: 2137,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/seafood_curry.png',
  },
  2138: {
    name: 'Monster Gelato',
    id: 2138,
    class: 'cooking-ingredient',
    itemImage: '/images/cooking/monster_gelato.png',
  },
};
